# Generated by Django 4.2 on 2023-04-10 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.CharField(max_length=100)),
                ('tasks_time', models.DateTimeField(verbose_name='Data da tarefa')),
            ],
        ),
        migrations.CreateModel(
            name='full_tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_complete', models.BooleanField(default=None)),
                ('complete_tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cabeça_Agenda.tarefas')),
            ],
        ),
    ]
